// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vwgkhksotewdbqwwvaie.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3Z2toa3NvdGV3ZGJxd3d2YWllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNDE4OTAsImV4cCI6MjA1NzYxNzg5MH0.PyV0g9oXX5GxkjluZcW0eCutVrGa96qKgXwKjzxrrX0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);